[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="reports/accueil.html"
    path = "/fr/index.html" #la racine du site

  [[plugins.inputs.audits]]
    output_path="reports/pagecontact.html"
    path = "/fr/contact.html" #la racine du site

  [[plugins.inputs.audits]]
    output_path="reports/pageartiste.html"
    path = "/fr/power.html" #la racine du site

  [[plugins.inputs.audits]]
    output_path="reports/pageoeuvre.html"
    path = "/fr/the_time.html" #la racine du site

  [[plugins.inputs.audits]]
    output_path="reports/billetterie.html"
    path = "/fr/billetterie.html" #la racine du site

